language: node_js
node_js:
  - "9.11"
  - "10.15"
  - "11.15"
  - "12.3"
cache:
  directories:
    - node_modules
script:
  # install optional modules for tests
  - npm i ejs handlebars pug co-body copy-to type-is

  - npm run lint
  - npm run coverage
  - npm run report-coverage
after_success:
  coveralls < ./coverage/lcov.info
