language: node_js
node_js:
  - "9.11"
  - "10.15"
  - "11.15"
  - "12.3"
cache:
  directories:
    - node_modules
script:
  # install modules needed for engine tests
  - npm i ejs handlebars pug

  - npm run lint
  - npm run test-cov
  - npm run coverage
after_script:
  coveralls < ./coverage/lcov.info
